import type { Plugin, VNodeChild } from 'vue';
import { expect, test } from 'vitest';
import { createApp, h } from 'vue';
import { BankaiButton, createBankai } from '../src/index';

interface Mounted {
  button: HTMLButtonElement;
  teardown: () => void;
}

// Default-slot content for a mount: a plain string, a render function for rich
// content (icons, multiple children), or `null` to omit the slot entirely.
type Slot = string | null | (() => VNodeChild);

// Mounts BankaiButton into the real browser DOM and returns the rendered root <button> plus a teardown.
// Dependency-free (no test-utils). Pass a plugin (e.g. createBankai(...)) to configure.
function mountButton(
  props: Record<string, unknown> = {},
  slot: Slot = 'Click me',
  plugin?: Plugin,
): Mounted {
  const host = document.createElement('div');
  document.body.append(host);
  // A `slot` of `null` mounts without a default slot, exercising the optional slot.
  const renderSlot = typeof slot === 'function' ? slot : (): VNodeChild => slot;
  const app = createApp(() =>
    slot === null ? h(BankaiButton, props) : h(BankaiButton, props, renderSlot),
  );
  if (plugin !== undefined) {
    app.use(plugin);
  }

  app.mount(host);

  const button = host.querySelector('button');
  if (button === null) {
    throw new Error('BankaiButton did not render a <button>');
  }

  return {
    button,
    teardown: () => {
      app.unmount();
      host.remove();
    },
  };
}

test('renders a native <button> with safe defaults', () => {
  const { button, teardown } = mountButton();

  expect(button.tagName).toBe('BUTTON');
  // `type` defaults to "button", not the HTML default "submit".
  expect(button.type).toBe('button');
  expect(button.classList.contains('bankai-button')).toBe(true);
  expect(button.dataset.part).toBe('root');
  expect(button.dataset.bankaiVariant).toBe('solid');
  expect(button.dataset.bankaiSize).toBe('md');
  expect(button.textContent).toContain('Click me');
  // An id is generated by default.
  expect(button.id).toMatch(/^bankai-button-/u);

  teardown();
});

test('uses a consumer-provided id over the generated one', () => {
  const { button, teardown } = mountButton({ id: 'save-button' });

  expect(button.id).toBe('save-button');

  teardown();
});

test('omits the id when generation is disabled via createBankai', () => {
  const { button, teardown } = mountButton({}, 'Click me', createBankai({ idGeneration: false }));
  expect(button.hasAttribute('id')).toBe(false);
  teardown();

  // A consumer id still applies even with generation disabled.
  const provided = mountButton(
    { id: 'explicit' },
    'Click me',
    createBankai({ idGeneration: false }),
  );
  expect(provided.button.id).toBe('explicit');
  provided.teardown();
});

test('treats an explicit empty-string id as an opt-out', () => {
  // Passing `id=""` opts this instance out of id generation:
  // the empty value is kept verbatim (it falls through onto the root) and no id is generated.
  const { button, teardown } = mountButton({ id: '' });

  expect(button.getAttribute('id')).toBe('');
  expect(button.id).not.toMatch(/^bankai-button-/u);

  teardown();
});

test('reflects variant/size and honors disabled', () => {
  const { button, teardown } = mountButton({ variant: 'outline', size: 'lg', disabled: true });

  expect(button.dataset.bankaiVariant).toBe('outline');
  expect(button.dataset.bankaiSize).toBe('lg');
  expect(button.disabled).toBe(true);

  teardown();
});

test('renders rich slot content', () => {
  const { button, teardown } = mountButton({}, () => [h('span', { class: 'icon' }, '★'), 'Save']);

  expect(button.querySelector('.icon')?.textContent).toBe('★');
  expect(button.textContent).toContain('Save');

  teardown();
});

test('renders without slot content', () => {
  const { button, teardown } = mountButton({}, null);

  expect(button.tagName).toBe('BUTTON');
  expect(button.textContent).toBe('');

  teardown();
});

test('forwards attributes/classes/events to the root button', () => {
  let clicks = 0;
  const { button, teardown } = mountButton(
    {
      'aria-label': 'Save',
      'data-testid': 'save',
      class: 'my-cta',
      onClick: () => {
        clicks += 1;
      },
    },
    'Save',
  );

  expect(button.getAttribute('aria-label')).toBe('Save');
  expect(button.dataset.testid).toBe('save');
  // Consumer classes merge with the component's own `bankai-button`.
  expect(button.classList.contains('bankai-button')).toBe(true);
  expect(button.classList.contains('my-cta')).toBe(true);

  button.click();
  expect(clicks).toBe(1);

  teardown();
});
