import type { Plugin } from 'vue';
import { expect, test } from 'vitest';
import { createApp, h, ref } from 'vue';
import { BankaiInput, createBankai } from '../src/index';

interface Mounted {
  input: HTMLInputElement;
  teardown: () => void;
}

// The shape BankaiInput exposes through a template ref. Declared locally rather than imported from
// the SFC's `BankaiInputExposes` so this runtime test doesn't pull a `.vue` type through the barrel
// (the exported type surface is locked separately in BankaiInput.test-d.ts).
interface InputExposes {
  readonly el: HTMLInputElement | null;
  focus: (options?: FocusOptions) => void;
  blur: () => void;
  select: () => void;
}

// Mounts BankaiInput into the real browser DOM and returns the rendered root <input> plus a teardown.
// Dependency-free (no test-utils). Pass a plugin (e.g. createBankai(...)) to configure.
function mountInput(props: Record<string, unknown> = {}, plugin?: Plugin): Mounted {
  const host = document.createElement('div');
  document.body.append(host);
  const app = createApp(() => h(BankaiInput, props));
  if (plugin !== undefined) {
    app.use(plugin);
  }

  app.mount(host);

  const input = host.querySelector('input');
  if (input === null) {
    throw new Error('BankaiInput did not render an <input>');
  }

  return {
    input,
    teardown: () => {
      app.unmount();
      host.remove();
    },
  };
}

test('renders a native <input> with safe defaults', () => {
  const { input, teardown } = mountInput();

  expect(input.tagName).toBe('INPUT');
  expect(input.type).toBe('text');
  expect(input.classList.contains('bankai-input')).toBe(true);
  expect(input.dataset.part).toBe('root');
  expect(input.dataset.bankaiSize).toBe('md');
  expect(input.disabled).toBe(false);
  expect(input.readOnly).toBe(false);
  // An id is generated by default.
  expect(input.id).toMatch(/^bankai-input-/u);

  teardown();
});

test('uses a consumer-provided id over the generated one', () => {
  const { input, teardown } = mountInput({ id: 'email-field' });

  expect(input.id).toBe('email-field');

  teardown();
});

test('omits the id when generation is disabled via createBankai', () => {
  const { input, teardown } = mountInput({}, createBankai({ idGeneration: false }));
  expect(input.hasAttribute('id')).toBe(false);
  teardown();

  // A consumer id still applies even with generation disabled.
  const provided = mountInput({ id: 'explicit' }, createBankai({ idGeneration: false }));
  expect(provided.input.id).toBe('explicit');
  provided.teardown();
});

test('treats an explicit empty-string id as an opt-out', () => {
  const { input, teardown } = mountInput({ id: '' });

  expect(input.getAttribute('id')).toBe('');
  expect(input.id).not.toMatch(/^bankai-input-/u);

  teardown();
});

test('reflects size/type and honors disabled/readonly', () => {
  const { input, teardown } = mountInput({
    type: 'email',
    size: 'lg',
    disabled: true,
    readonly: true,
  });

  expect(input.type).toBe('email');
  expect(input.dataset.bankaiSize).toBe('lg');
  expect(input.disabled).toBe(true);
  expect(input.readOnly).toBe(true);

  teardown();
});

test('reflects a custom size verbatim as data-* (escape hatch)', () => {
  const { input, teardown } = mountInput({ size: 'xl' });

  expect(input.dataset.bankaiSize).toBe('xl');

  teardown();
});

test('a plain-specificity consumer rule targeting a custom size wins', () => {
  // Prove the escape hatch works end-to-end: a consumer stylesheet keyed on the reflected `data-*`
  // (ordinary specificity, NOT `:where()`) applies to a custom size (SPEC.md §4.4/§4.6).
  const style = document.createElement('style');
  style.textContent = `[data-bankai-size='xl'] { letter-spacing: 3px; }`;
  document.head.append(style);

  const { input, teardown } = mountInput({ size: 'xl' });
  expect(getComputedStyle(input).letterSpacing).toBe('3px');

  teardown();
  style.remove();
});

test('two-way binds the value via v-model', () => {
  const host = document.createElement('div');
  document.body.append(host);
  let emitted: string | undefined;
  const app = createApp(() =>
    h(BankaiInput, {
      modelValue: 'hello',
      'onUpdate:modelValue': (v: string | undefined) => {
        emitted = v;
      },
    }),
  );
  app.mount(host);

  const input = host.querySelector('input')!;
  // Model → DOM.
  expect(input.value).toBe('hello');

  // DOM → model (emits update:modelValue with the new value).
  input.value = 'world';
  input.dispatchEvent(new Event('input'));
  expect(emitted).toBe('world');

  app.unmount();
  host.remove();
});

test('exposes el and focus/blur/select through a template ref', () => {
  const host = document.createElement('div');
  document.body.append(host);
  const inputRef = ref<InputExposes | null>(null);
  const app = createApp(() => h(BankaiInput, { ref: inputRef }));
  app.mount(host);

  const api = inputRef.value!;
  const input = host.querySelector('input')!;

  expect(api.el).toBe(input);

  api.focus();
  expect(document.activeElement).toBe(input);

  api.blur();
  expect(document.activeElement).not.toBe(input);

  input.value = 'select me';
  api.focus();
  api.select();
  expect(input.selectionStart).toBe(0);
  expect(input.selectionEnd).toBe(input.value.length);

  app.unmount();
  host.remove();
});

test('forwards attributes/classes/events to the root input', () => {
  let inputs = 0;
  const { input, teardown } = mountInput({
    'aria-label': 'Email',
    'data-testid': 'email',
    class: 'my-field',
    placeholder: 'you@example.com',
    name: 'email',
    onInput: () => {
      inputs += 1;
    },
  });

  expect(input.getAttribute('aria-label')).toBe('Email');
  expect(input.dataset.testid).toBe('email');
  expect(input.placeholder).toBe('you@example.com');
  expect(input.name).toBe('email');
  // Consumer classes merge with the component's own `bankai-input`.
  expect(input.classList.contains('bankai-input')).toBe(true);
  expect(input.classList.contains('my-field')).toBe(true);

  input.dispatchEvent(new Event('input'));
  expect(inputs).toBe(1);

  teardown();
});
