import type { Plugin } from 'vue';
import { expect, test } from 'vitest';
import { createApp, h, nextTick, ref } from 'vue';
import de from '../src/i18n/locales/de';
import { BankaiInputPassword, createBankai } from '../src/index';

interface Mounted {
  host: HTMLElement;
  input: HTMLInputElement;
  wrapper: HTMLDivElement | null;
  toggle: HTMLButtonElement | null;
  teardown: () => void;
}

// The shape BankaiInputPassword exposes through a template ref. Declared locally rather than imported from
// the SFC's `BankaiInputPasswordExposes` so this runtime test doesn't pull a `.vue` type through the barrel
// (the exported type surface is locked separately in BankaiInputPassword.test-d.ts).
interface InputPasswordExposes {
  readonly el: HTMLInputElement | null;
  focus: (options?: FocusOptions) => void;
  blur: () => void;
  select: () => void;
}

// Mounts BankaiInputPassword into the real browser DOM and returns its anatomy plus a teardown. `wrapper`
// and `toggle` are `null` in the bare shape (`toggle: false`). Dependency-free (no test-utils).
function mount(props: Record<string, unknown> = {}, plugin?: Plugin): Mounted {
  const host = document.createElement('div');
  document.body.append(host);
  const app = createApp(() => h(BankaiInputPassword, props));
  if (plugin !== undefined) {
    app.use(plugin);
  }

  app.mount(host);

  const input = host.querySelector('input');
  if (!input) {
    throw new Error('BankaiInputPassword did not render an <input>');
  }

  return {
    host,
    input,
    wrapper: host.querySelector<HTMLDivElement>('.bankai-input-password'),
    toggle: host.querySelector<HTMLButtonElement>('[data-part="toggle"]'),
    teardown: () => {
      app.unmount();
      host.remove();
    },
  };
}

test('renders a masked field wrapped with a reveal button by default', () => {
  const { input, wrapper, toggle, teardown } = mount();

  expect(input.tagName).toBe('INPUT');
  expect(input.type).toBe('password');
  expect(input.classList.contains('bankai-input')).toBe(true);
  // The wrapper is the root; the field is nested with data-part="field".
  expect(wrapper).not.toBeNull();
  expect(wrapper!.dataset.part).toBe('root');
  expect(input.dataset.part).toBe('field');
  expect(input.dataset.bankaiSize).toBe('md');
  // Masked by default → no `data-bankai-revealed` presence flag.
  expect(Object.hasOwn(wrapper!.dataset, 'bankaiRevealed')).toBe(false);

  // The reveal button is a real, focusable, tab-order control (not aria-hidden / tabindex="-1").
  expect(toggle).not.toBeNull();
  expect(toggle!.type).toBe('button');
  expect(toggle!.hasAttribute('aria-hidden')).toBe(false);
  expect(toggle!.hasAttribute('tabindex')).toBe(false);
  expect(toggle!.getAttribute('aria-label')).toBe('Show password');

  // An id is generated by default, on the field.
  expect(input.id).toMatch(/^bankai-input-password-/u);

  teardown();
});

test('renders a bare masked input with no wrapper/button when toggle is false', () => {
  const { input, wrapper, toggle, teardown } = mount({ toggle: false });

  expect(input.type).toBe('password');
  expect(input.dataset.part).toBe('root');
  expect(wrapper).toBeNull();
  expect(toggle).toBeNull();

  teardown();
});

test('the reveal button flips the field type and swaps its accessible name', async () => {
  const { input, wrapper, toggle, teardown } = mount();

  expect(input.type).toBe('password');
  toggle!.click();
  await nextTick();
  expect(input.type).toBe('text');
  expect(toggle!.getAttribute('aria-label')).toBe('Hide password');
  expect(Object.hasOwn(wrapper!.dataset, 'bankaiRevealed')).toBe(true);

  toggle!.click();
  await nextTick();
  expect(input.type).toBe('password');
  expect(toggle!.getAttribute('aria-label')).toBe('Show password');
  expect(Object.hasOwn(wrapper!.dataset, 'bankaiRevealed')).toBe(false);

  teardown();
});

test('v-model:revealed drives the type even when the built-in toggle is off', async () => {
  const revealed = ref(false);
  const host = document.createElement('div');
  document.body.append(host);
  const app = createApp(() =>
    h(BankaiInputPassword, {
      toggle: false,
      revealed: revealed.value,
      'onUpdate:revealed': (v: boolean) => {
        revealed.value = v;
      },
    }),
  );
  app.mount(host);
  const input = host.querySelector('input')!;

  expect(input.type).toBe('password');
  revealed.value = true;
  await nextTick();
  expect(input.type).toBe('text');

  app.unmount();
  host.remove();
});

test('round-trips the string v-model', () => {
  const host = document.createElement('div');
  document.body.append(host);
  const model = ref<string | undefined>(undefined);
  const app = createApp(() =>
    h(BankaiInputPassword, {
      modelValue: model.value,
      'onUpdate:modelValue': (v: string | undefined) => {
        model.value = v;
      },
    }),
  );
  app.mount(host);
  const input = host.querySelector('input')!;

  input.value = 'hunter2';
  input.dispatchEvent(new Event('input'));
  expect(model.value).toBe('hunter2');

  app.unmount();
  host.remove();
});

test('disabled turns off the field and the reveal button; readonly leaves the button usable', async () => {
  const disabled = mount({ disabled: true });
  expect(disabled.input.disabled).toBe(true);
  expect(disabled.toggle!.disabled).toBe(true);
  disabled.teardown();

  // A read-only field can still be revealed — the button stays enabled.
  const readonly = mount({ readonly: true });
  expect(readonly.input.readOnly).toBe(true);
  expect(readonly.toggle!.disabled).toBe(false);
  readonly.toggle!.click();
  await nextTick();
  expect(readonly.input.type).toBe('text');
  readonly.teardown();
});

// Regression: a bare `disabled` attribute (`<BankaiInputPassword disabled />`) reaches the prop as the empty
// string `''`. The prop must be typed so the Vue compiler casts `''` → true; an indirect alias would leave
// `disabled` uncast, so the reveal-button disable logic silently no-ops. Passing `''` mirrors the bare form.
test('casts a bare disabled attribute so the button-disable logic fires', () => {
  const { input, toggle, teardown } = mount({ disabled: '' });
  expect(input.disabled).toBe(true);
  expect(toggle!.disabled).toBe(true);
  teardown();
});

test('routes class/style to the wrapper and form attributes to the field (toggle mode)', () => {
  const { input, wrapper, teardown } = mount({
    class: 'my-field',
    name: 'password',
    autocomplete: 'current-password',
    'aria-label': 'Password',
  });

  expect(wrapper!.classList.contains('bankai-input-password')).toBe(true);
  expect(wrapper!.classList.contains('my-field')).toBe(true);
  expect(input.classList.contains('my-field')).toBe(false);

  expect(input.name).toBe('password');
  expect(input.getAttribute('autocomplete')).toBe('current-password');
  expect(input.getAttribute('aria-label')).toBe('Password');

  teardown();
});

test('in bare mode class merges onto the root input alongside bankai-input', () => {
  const { input, teardown } = mount({ toggle: false, class: 'my-field' });
  expect(input.classList.contains('bankai-input')).toBe(true);
  expect(input.classList.contains('my-field')).toBe(true);
  teardown();
});

test('resolves the reveal label from a per-instance prop and the i18n config', async () => {
  const prop = mount({ showLabel: 'Reveal' });
  expect(prop.toggle!.getAttribute('aria-label')).toBe('Reveal');
  prop.teardown();

  const german = mount({}, createBankai({ i18n: { locale: 'de', messages: { de } } }));
  expect(german.toggle!.getAttribute('aria-label')).toBe('Passwort anzeigen');
  german.toggle!.click();
  await nextTick();
  expect(german.toggle!.getAttribute('aria-label')).toBe('Passwort verbergen');
  german.teardown();
});

test('omits the generated id when disabled via createBankai', () => {
  const { input, teardown } = mount({}, createBankai({ idGeneration: false }));
  expect(input.hasAttribute('id')).toBe(false);
  teardown();
});

test('exposes el and focus/blur/select through a template ref', () => {
  const host = document.createElement('div');
  document.body.append(host);
  const api = ref<InputPasswordExposes | null>(null);
  const app = createApp(() => h(BankaiInputPassword, { ref: api }));
  app.mount(host);

  const input = host.querySelector('input')!;
  const exposed = api.value!;

  expect(exposed.el).toBe(input);
  exposed.focus();
  expect(document.activeElement).toBe(input);
  exposed.blur();
  expect(document.activeElement).not.toBe(input);

  app.unmount();
  host.remove();
});
