import type { Plugin } from 'vue';
import { expect, test } from 'vitest';
import { createApp, h, ref } from 'vue';
import { BankaiInputNumber, createBankai } from '../src/index';

interface Mounted {
  host: HTMLElement;
  input: HTMLInputElement;
  wrapper: HTMLDivElement | null;
  decrement: HTMLButtonElement | null;
  increment: HTMLButtonElement | null;
  teardown: () => void;
}

// The shape BankaiInputNumber exposes through a template ref. Declared locally rather than imported from
// the SFC's `BankaiInputNumberExposes` so this runtime test doesn't pull a `.vue` type through the barrel
// (the exported type surface is locked separately in BankaiInputNumber.test-d.ts).
interface InputNumberExposes {
  readonly el: HTMLInputElement | null;
  focus: (options?: FocusOptions) => void;
  blur: () => void;
  select: () => void;
  stepUp: (count?: number) => void;
  stepDown: (count?: number) => void;
}

// Mounts BankaiInputNumber into the real browser DOM and returns its anatomy plus a teardown. `wrapper`
// and the two controls are `null` in the default bare shape (no `buttons`). Dependency-free (no test-utils).
function mount(props: Record<string, unknown> = {}, plugin?: Plugin): Mounted {
  const host = document.createElement('div');
  document.body.append(host);
  const app = createApp(() => h(BankaiInputNumber, props));
  if (plugin !== undefined) {
    app.use(plugin);
  }

  app.mount(host);

  const input = host.querySelector('input');
  if (!input) {
    throw new Error('BankaiInputNumber did not render an <input>');
  }

  return {
    host,
    input,
    wrapper: host.querySelector<HTMLDivElement>('.bankai-input-number'),
    decrement: host.querySelector<HTMLButtonElement>('[data-part="decrement"]'),
    increment: host.querySelector<HTMLButtonElement>('[data-part="increment"]'),
    teardown: () => {
      app.unmount();
      host.remove();
    },
  };
}

test('renders a bare native number input by default — no wrapper, no controls', () => {
  const { input, wrapper, decrement, increment, teardown } = mount();

  expect(input.tagName).toBe('INPUT');
  expect(input.type).toBe('number');
  expect(input.classList.contains('bankai-input')).toBe(true);
  // The bare input is itself the root; there is no wrapper and no stepper controls.
  expect(input.dataset.part).toBe('root');
  expect(wrapper).toBeNull();
  expect(decrement).toBeNull();
  expect(increment).toBeNull();
  expect(input.dataset.bankaiSize).toBe('md');
  // An id is generated by default.
  expect(input.id).toMatch(/^bankai-input-number-/u);

  teardown();
});

test('defaults inputmode from step (integer → numeric, fractional → decimal), overridable', () => {
  const integer = mount();
  expect(integer.input.getAttribute('inputmode')).toBe('numeric');
  integer.teardown();

  const fractional = mount({ step: 0.5 });
  expect(fractional.input.getAttribute('inputmode')).toBe('decimal');
  fractional.teardown();

  const explicit = mount({ step: 0.5, inputmode: 'numeric' });
  expect(explicit.input.getAttribute('inputmode')).toBe('numeric');
  explicit.teardown();
});

test('wraps the field and renders stepper controls when buttons is set', () => {
  const { input, wrapper, decrement, increment, teardown } = mount({ buttons: true });

  expect(wrapper).not.toBeNull();
  expect(wrapper!.dataset.part).toBe('root');
  // `buttons: true` resolves to the default 'stacked' layout, reflected for the theme.
  expect(wrapper!.dataset.bankaiButtons).toBe('stacked');
  // The field is now nested with data-part="field".
  expect(input.dataset.part).toBe('field');
  expect(input.classList.contains('bankai-input')).toBe(true);

  for (const btn of [decrement!, increment!]) {
    expect(btn.type).toBe('button');
    expect(btn.getAttribute('tabindex')).toBe('-1');
    expect(btn.getAttribute('aria-hidden')).toBe('true');
  }

  teardown();
});

test('reflects a string buttons value verbatim as the layout (escape hatch)', () => {
  const split = mount({ buttons: 'split' });
  expect(split.wrapper!.dataset.bankaiButtons).toBe('split');
  split.teardown();

  const custom = mount({ buttons: 'my-layout' });
  expect(custom.wrapper!.dataset.bankaiButtons).toBe('my-layout');
  custom.teardown();
});

test('parses the typed string into a number v-model, empty → undefined', () => {
  const host = document.createElement('div');
  document.body.append(host);
  const emitted: Array<number | undefined> = [];
  const app = createApp(() =>
    h(BankaiInputNumber, {
      'onUpdate:modelValue': (v: number | undefined) => {
        emitted.push(v);
      },
    }),
  );
  app.mount(host);
  const input = host.querySelector('input')!;

  input.value = '42';
  input.dispatchEvent(new Event('input'));
  expect(emitted.at(-1)).toBe(42);

  // Cleared field → undefined, never coerced to 0.
  input.value = '';
  input.dispatchEvent(new Event('input'));
  expect(emitted.at(-1)).toBeUndefined();

  app.unmount();
  host.remove();
});

test('parses a decimal entry without reformatting (no clobber)', () => {
  const host = document.createElement('div');
  document.body.append(host);
  const model = ref<number | undefined>(undefined);
  const app = createApp(() =>
    h(BankaiInputNumber, {
      modelValue: model.value,
      'onUpdate:modelValue': (v: number | undefined) => {
        model.value = v;
      },
    }),
  );
  app.mount(host);
  const input = host.querySelector('input')!;

  // A decimal parses to its number, and the exact string entered survives — the number bridge mirrors the
  // DOM rather than reformatting it, so `1.50` is never rewritten to `1.5`.
  input.value = '1.50';
  input.dispatchEvent(new Event('input'));
  expect(model.value).toBe(1.5);
  expect(input.value).toBe('1.50');

  app.unmount();
  host.remove();
});

test('the stepper controls drive the native step and update the model', () => {
  const host = document.createElement('div');
  document.body.append(host);
  const emitted: Array<number | undefined> = [];
  const app = createApp(() =>
    h(BankaiInputNumber, {
      buttons: true,
      modelValue: 5,
      'onUpdate:modelValue': (v: number | undefined) => {
        emitted.push(v);
      },
    }),
  );
  app.mount(host);
  const increment = host.querySelector<HTMLButtonElement>('[data-part="increment"]')!;
  const decrement = host.querySelector<HTMLButtonElement>('[data-part="decrement"]')!;
  const input = host.querySelector('input')!;

  increment.click();
  expect(input.value).toBe('6');
  expect(emitted.at(-1)).toBe(6);

  decrement.click();
  expect(input.value).toBe('5');
  expect(emitted.at(-1)).toBe(5);

  app.unmount();
  host.remove();
});

test('disables the controls at the bounds', () => {
  const atMax = mount({ buttons: true, modelValue: 10, min: 0, max: 10 });
  expect(atMax.increment!.disabled).toBe(true);
  expect(atMax.decrement!.disabled).toBe(false);
  atMax.teardown();

  const atMin = mount({ buttons: true, modelValue: 0, min: 0, max: 10 });
  expect(atMin.decrement!.disabled).toBe(true);
  expect(atMin.increment!.disabled).toBe(false);
  atMin.teardown();
});

test('honors disabled/readonly on the field and both controls', () => {
  const disabled = mount({ buttons: true, disabled: true });
  expect(disabled.input.disabled).toBe(true);
  expect(disabled.decrement!.disabled).toBe(true);
  expect(disabled.increment!.disabled).toBe(true);
  disabled.teardown();

  const readonly = mount({ buttons: true, readonly: true });
  expect(readonly.input.readOnly).toBe(true);
  expect(readonly.decrement!.disabled).toBe(true);
  expect(readonly.increment!.disabled).toBe(true);
  readonly.teardown();
});

// Regression: a bare `disabled`/`buttons` attribute (`<BankaiInputNumber disabled buttons />`) reaches the
// prop as the empty string `''`. The props must be typed so the Vue compiler casts `''` → true; an indirect
// `HTMLInputElement['disabled']` alias leaves `disabled` uncast, so the control-disable logic silently
// no-ops. Passing `''` here mirrors the bare-attribute form.
test('casts bare disabled/buttons attributes so the logic fires', () => {
  const { input, wrapper, decrement, increment, teardown } = mount({ disabled: '', buttons: '' });
  // bare `buttons` → true → wrapper + controls; bare `disabled` → true → field + both controls disabled.
  expect(wrapper).not.toBeNull();
  expect(input.disabled).toBe(true);
  expect(decrement!.disabled).toBe(true);
  expect(increment!.disabled).toBe(true);
  teardown();
});

test('routes class/style to the wrapper and form attributes to the field (buttons mode)', () => {
  const { input, wrapper, teardown } = mount({
    buttons: true,
    class: 'my-field',
    name: 'quantity',
    'aria-label': 'Quantity',
  });

  expect(wrapper!.classList.contains('bankai-input-number')).toBe(true);
  expect(wrapper!.classList.contains('my-field')).toBe(true);
  expect(input.classList.contains('my-field')).toBe(false);

  expect(input.name).toBe('quantity');
  expect(input.getAttribute('aria-label')).toBe('Quantity');

  teardown();
});

test('in bare mode class merges onto the root input alongside bankai-input', () => {
  const { input, teardown } = mount({ class: 'my-field' });
  expect(input.classList.contains('bankai-input')).toBe(true);
  expect(input.classList.contains('my-field')).toBe(true);
  teardown();
});

test('omits the generated id when disabled via createBankai', () => {
  const { input, teardown } = mount({}, createBankai({ idGeneration: false }));
  expect(input.hasAttribute('id')).toBe(false);
  teardown();
});

test('exposes el, focus/blur/select, and stepUp/stepDown through a template ref', () => {
  const host = document.createElement('div');
  document.body.append(host);
  const api = ref<InputNumberExposes | null>(null);
  // No `buttons`: the stepper API works on the bare field too.
  const app = createApp(() => h(BankaiInputNumber, { ref: api, modelValue: 5 }));
  app.mount(host);

  const input = host.querySelector('input')!;
  const exposed = api.value!;

  expect(exposed.el).toBe(input);
  exposed.focus();
  expect(document.activeElement).toBe(input);
  exposed.blur();
  expect(document.activeElement).not.toBe(input);

  exposed.stepUp();
  expect(input.value).toBe('6');
  exposed.stepDown(2);
  expect(input.value).toBe('4');

  app.unmount();
  host.remove();
});
