<script setup lang="ts">
// The docs-site language switcher (header). ONE control drives BOTH i18n systems at once:
//   - the docs SITE locale (@nuxtjs/i18n) — nav/chrome/prose + the localized route (/ ↔ /de);
//   - bankai-vue's COMPONENT locale (config.i18n.locale) — every BankaiCodeBlock's copy label, etc.
// It only sets @nuxtjs/i18n here; a universal plugin (plugins/bankai-locale-sync.ts) mirrors the
// active locale into config.i18n.locale on server + client, so /de SSRs German for both systems with
// no hydration mismatch. The two systems stay separate (distinct config/messages/coverage) — only the
// active locale is synced. Replaces the earlier LocaleToggle, which flipped bankai's locale alone.
//
// `setLocale` navigates to the localized route (prefix_except_default), so the choice is reflected in
// the URL and survives reload/SSG — stronger than the old session-only demo.
//
// Two mutually-exclusive options → a WAI-ARIA radiogroup with a roving tabindex, matching the
// ColorSchemeToggle beside it (SPEC §4.16).
import type { ComponentPublicInstance } from 'vue';
import { computed, ref } from 'vue';

const { locale, locales, setLocale, t } = useI18n();

// The strict locale union (`'en' | 'de'`) generated by @nuxtjs/i18n — `setLocale` expects it.
type LocaleCode = typeof locale.value;

// Short label from the code (EN/DE); the full name drives the accessible label.
const options = computed(() =>
  locales.value.map((entry) => ({
    code: entry.code,
    label: entry.code.toUpperCase(),
    name: entry.name ?? entry.code,
  })),
);

const group = ref<ComponentPublicInstance | null>(null);

function select(next: LocaleCode): void {
  if (next !== locale.value) {
    void setLocale(next);
  }
}

// Roving tabindex: move focus to the radio that just became selected.
function focusOption(index: number): void {
  const root = group.value?.$el as HTMLElement | undefined;
  root?.querySelectorAll<HTMLButtonElement>('button')[index]?.focus();
}

// Arrow keys cycle the selection (WAI-ARIA radiogroup pattern); preventDefault stops page scroll.
function onKeydown(event: KeyboardEvent): void {
  const forward = event.key === 'ArrowRight' || event.key === 'ArrowDown';
  const backward = event.key === 'ArrowLeft' || event.key === 'ArrowUp';
  if (!forward && !backward) {
    return;
  }
  event.preventDefault();
  const list = options.value;
  const current = list.findIndex((opt) => opt.code === locale.value);
  const nextIndex = (current + (forward ? 1 : -1) + list.length) % list.length;
  const nextOption = list[nextIndex];
  if (!nextOption) {
    return;
  }
  select(nextOption.code);
  focusOption(nextIndex);
}
</script>

<template>
  <BankaiFlex
    ref="group"
    align="center"
    gap="1"
    role="radiogroup"
    :aria-label="t('switcher.label')"
    @keydown="onKeydown"
  >
    <BankaiButton
      v-for="opt in options"
      :key="opt.code"
      size="sm"
      role="radio"
      :variant="locale === opt.code ? 'solid' : 'ghost'"
      :aria-checked="locale === opt.code"
      :aria-label="opt.name"
      :tabindex="locale === opt.code ? 0 : -1"
      @click="select(opt.code)"
    >
      {{ opt.label }}
    </BankaiButton>
  </BankaiFlex>
</template>
