<script setup lang="ts">
// The docs-site language switcher (header). ONE control drives BOTH i18n systems at once:
//   - the docs SITE locale (@nuxtjs/i18n) — nav/chrome/prose + the localized route (/ ↔ /de);
//   - bankai-vue's COMPONENT locale (config.i18n.locale) — every BankaiCodeBlock's copy label, etc.
// It only sets @nuxtjs/i18n here; a universal plugin (plugins/bankai-locale-sync.ts) mirrors the
// active locale into config.i18n.locale on server + client, so /de SSRs German for both systems with
// no hydration mismatch. The two systems stay separate (distinct config/messages/coverage) — only the
// active locale is synced. Replaces the earlier LocaleToggle, which flipped bankai's locale alone.
//
// `setLocale` navigates to the localized route (prefix_except_default), so the choice is reflected in
// the URL and survives reload/SSG — stronger than the old session-only demo.
//
// Two mutually-exclusive options → a WAI-ARIA radiogroup with a roving tabindex, matching the
// ColorSchemeToggle beside it (SPEC §4.16); the keyboard behaviour is shared via useRovingRadiogroup.
import { useRovingRadiogroup } from '../composables/useRovingRadiogroup';

const { locale, locales, setLocale, t } = useI18n();

// The strict locale union (`'en' | 'de'`) generated by @nuxtjs/i18n — `setLocale` expects it.
type LocaleCode = typeof locale.value;

function select(next: LocaleCode): void {
  if (next !== locale.value) {
    void setLocale(next);
  }
}

const { group, onKeydown } = useRovingRadiogroup<LocaleCode>(
  () => locales.value.map((entry) => entry.code),
  () => locale.value,
  select,
);
</script>

<template>
  <BankaiFlex
    ref="group"
    align="center"
    gap="1"
    role="radiogroup"
    :aria-label="t('switcher.label')"
    @keydown="onKeydown"
  >
    <!-- Short label from the code (EN/DE); the full name drives the accessible label. -->
    <BankaiButton
      v-for="entry in locales"
      :key="entry.code"
      size="sm"
      role="radio"
      :variant="locale === entry.code ? 'solid' : 'ghost'"
      :aria-checked="locale === entry.code"
      :aria-label="entry.name ?? entry.code"
      :tabindex="locale === entry.code ? 0 : -1"
      @click="select(entry.code)"
    >
      {{ entry.code.toUpperCase() }}
    </BankaiButton>
  </BankaiFlex>
</template>
