// AUTO-GENERATED by scripts/generate-component-meta.ts — do not edit by hand.
// Regenerate with `pnpm docs:meta`. Props/slots/events, defaults, and descriptions come from
// @bankai-vue/core's source SFCs; the `type` column merges auto types with curated overrides.
// This file is excluded from oxfmt so the `--check` staleness comparison stays byte-exact.
/* eslint-disable */

export interface MetaProp {
  name: string;
  type: string;
  default?: string;
  required: boolean;
  description: string;
}

export interface MetaSlot {
  name: string;
  description: string;
}

export interface MetaEvent {
  name: string;
  type: string;
  description: string;
}

export interface MetaExpose {
  name: string;
  type: string;
  description: string;
}

export interface MetaThemeToken {
  name: string;
  value: string;
}

export interface ComponentMeta {
  props: MetaProp[];
  slots: MetaSlot[];
  events: MetaEvent[];
  exposed: MetaExpose[];
  /**
   * CSS custom-property token surface per theme (the `--bankai-<component>-*` declarations with their
   * default value). Keyed by theme so the docs table can switch with the active theme; `bankai` (the house
   * theme) is populated today. Token *purpose* prose is localized in the docs i18n messages, keyed by token
   * name — it is theme-independent.
   */
  theming: { bankai: MetaThemeToken[] };
}

export const componentMeta = {
  "BankaiApp": {
    "props": [],
    "slots": [
      {
        "name": "default",
        "description": "The whole application — typically a BankaiLayout (or a standalone region shell) and its routes."
      }
    ],
    "events": [],
    "exposed": [],
    "theming": {
      "bankai": []
    }
  },
  "BankaiAside": {
    "props": [
      {
        "name": "label",
        "type": "string",
        "required": false,
        "description": "Accessible name for the region, set as aria-label. A page can have several complementary landmarks, so label each one (e.g. \"Secondary navigation\", \"Filters\") to tell them apart in a screen reader's landmark list. Omit for a single, unambiguous aside. A consumer's own aria-label / aria-labelledby fallthrough takes precedence over this default."
      }
    ],
    "slots": [
      {
        "name": "default",
        "description": "Side-rail content — typically a BankaiSidebar (sections, collapsible groups)."
      }
    ],
    "events": [],
    "exposed": [],
    "theming": {
      "bankai": [
        {
          "name": "--bankai-aside-padding-block",
          "value": "var(--bankai-space-8)"
        },
        {
          "name": "--bankai-aside-padding-inline",
          "value": "var(--bankai-space-8)"
        },
        {
          "name": "--bankai-aside-border-width",
          "value": "1px"
        },
        {
          "name": "--bankai-aside-border-color",
          "value": "var(--bankai-color-border)"
        },
        {
          "name": "--bankai-aside-background",
          "value": "var(--bankai-color-bg)"
        }
      ]
    }
  },
  "BankaiButton": {
    "props": [
      {
        "name": "variant",
        "type": "'solid' | 'outline' | 'ghost' | (string)",
        "required": false,
        "description": "Visual variant. A named house variant (solid/outline/ghost) is themed; any other string reflects verbatim as data-bankai-variant as an escape hatch for a custom consumer-styled variant.",
        "default": "'solid'"
      },
      {
        "name": "size",
        "type": "'sm' | 'md' | 'lg' | (string)",
        "required": false,
        "description": "Size scale. A named step (sm/md/lg) is themed; any other string reflects verbatim as data-bankai-size as an escape hatch for a custom consumer-styled size.",
        "default": "'md'"
      },
      {
        "name": "type",
        "type": "'submit' | 'reset' | 'button'",
        "required": false,
        "description": "Native button type. Defaults to 'button' rather than the HTML default 'submit', so the button never submits a surrounding form by accident.",
        "default": "'button'"
      },
      {
        "name": "disabled",
        "type": "boolean",
        "required": false,
        "description": "Disable the button via the native disabled attribute.",
        "default": "false"
      }
    ],
    "slots": [
      {
        "name": "default",
        "description": "Button content — label and/or icons."
      }
    ],
    "events": [],
    "exposed": [],
    "theming": {
      "bankai": [
        {
          "name": "--bankai-button-fg",
          "value": "var(--bankai-color-primary-fg)"
        },
        {
          "name": "--bankai-button-bg",
          "value": "var(--bankai-color-primary)"
        },
        {
          "name": "--bankai-button-bg-hover",
          "value": "color-mix(in oklch, var(--bankai-button-bg), black 12%)"
        },
        {
          "name": "--bankai-button-bg-active",
          "value": "color-mix(in oklch, var(--bankai-button-bg), black 20%)"
        },
        {
          "name": "--bankai-button-bg-hover-quiet",
          "value": "color-mix(in oklch, currentcolor 8%, transparent)"
        },
        {
          "name": "--bankai-button-bg-active-quiet",
          "value": "color-mix(in oklch, currentcolor 14%, transparent)"
        },
        {
          "name": "--bankai-button-border-width",
          "value": "1px"
        },
        {
          "name": "--bankai-button-border-style",
          "value": "solid"
        },
        {
          "name": "--bankai-button-border-color",
          "value": "transparent"
        },
        {
          "name": "--bankai-button-radius",
          "value": "var(--bankai-radius)"
        },
        {
          "name": "--bankai-button-display",
          "value": "inline-flex"
        },
        {
          "name": "--bankai-button-align",
          "value": "center"
        },
        {
          "name": "--bankai-button-gap",
          "value": "var(--bankai-space-4)"
        },
        {
          "name": "--bankai-button-font",
          "value": "inherit"
        },
        {
          "name": "--bankai-button-cursor",
          "value": "pointer"
        },
        {
          "name": "--bankai-button-transition",
          "value": "background-color 150ms ease, border-color 150ms ease, color 150ms ease"
        },
        {
          "name": "--bankai-button-focus-ring",
          "value": "var(--bankai-focus-ring)"
        },
        {
          "name": "--bankai-button-focus-outline-width",
          "value": "2px"
        },
        {
          "name": "--bankai-button-focus-outline-offset",
          "value": "2px"
        },
        {
          "name": "--bankai-button-disabled-opacity",
          "value": "0.5"
        },
        {
          "name": "--bankai-button-disabled-cursor",
          "value": "not-allowed"
        },
        {
          "name": "--bankai-button-sm-padding-y",
          "value": "var(--bankai-space-1)"
        },
        {
          "name": "--bankai-button-sm-padding-x",
          "value": "var(--bankai-space-4)"
        },
        {
          "name": "--bankai-button-sm-font-size",
          "value": "var(--bankai-text-size-sm)"
        },
        {
          "name": "--bankai-button-md-padding-y",
          "value": "var(--bankai-space-3)"
        },
        {
          "name": "--bankai-button-md-padding-x",
          "value": "var(--bankai-space-6)"
        },
        {
          "name": "--bankai-button-md-font-size",
          "value": "var(--bankai-text-size-md)"
        },
        {
          "name": "--bankai-button-lg-padding-y",
          "value": "var(--bankai-space-4)"
        },
        {
          "name": "--bankai-button-lg-padding-x",
          "value": "var(--bankai-space-8)"
        },
        {
          "name": "--bankai-button-lg-font-size",
          "value": "var(--bankai-text-size-lg)"
        }
      ]
    }
  },
  "BankaiCodeBlock": {
    "props": [
      {
        "name": "code",
        "type": "string",
        "required": true,
        "description": "The code as a string. It is the source of truth for the clipboard (the copy button writes exactly this) and, when the default slot is not used, the text rendered inside the <code>."
      },
      {
        "name": "language",
        "type": "string",
        "required": false,
        "description": "Language identifier. Reflected verbatim as the language-<language> class on the <code> — the de-facto convention a BYO syntax highlighter (Shiki, Prism, highlight.js) or CSS keys off. Core itself highlights nothing."
      },
      {
        "name": "copyable",
        "type": "boolean",
        "required": false,
        "description": "Render the copy-to-clipboard button (and its role=\"status\" live region). Set false to omit it.",
        "default": "true"
      },
      {
        "name": "copy-label",
        "type": "string",
        "required": false,
        "description": "The copy button's accessible name and its idle label text (when the copy slot is not used). Overrides the resolved codeBlock.copy message for this block; unset, it resolves through the global i18n config (BankaiI18nConfig ), defaulting to the English 'Copy'."
      },
      {
        "name": "copied-label",
        "type": "string",
        "required": false,
        "description": "The button's label text after a successful copy (when the copy slot is not used) and the message announced by the role=\"status\" live region. Overrides the resolved codeBlock.copied message for this block; unset, it resolves through the global i18n config (BankaiI18nConfig ), defaulting to the English 'Copied'."
      },
      {
        "name": "copied-duration",
        "type": "number",
        "required": false,
        "description": "How long (ms) the copy button stays in its \"copied\" state after a successful copy before reverting to idle. Overrides the global codeBlock.copiedDuration config (BankaiConfig ) for this block."
      }
    ],
    "slots": [
      {
        "name": "default",
        "description": "Rendered code body — an escape hatch for pre-highlighted markup (e.g. a BYO highlighter's output). When omitted, the raw code prop renders verbatim as text. Either way the copy button writes the code prop, so the copied text stays exact regardless of what is rendered."
      },
      {
        "name": "copy",
        "description": "Copy-button content. Receives the current copied state so a consumer can swap label/icon. When omitted, the button shows the copyLabel / copiedLabel text."
      }
    ],
    "events": [],
    "exposed": [],
    "theming": {
      "bankai": [
        {
          "name": "--bankai-code-block-bg",
          "value": "var(--bankai-color-surface)"
        },
        {
          "name": "--bankai-code-block-font-family",
          "value": "var(--bankai-font-mono)"
        },
        {
          "name": "--bankai-code-block-font-size",
          "value": "var(--bankai-text-size-sm)"
        },
        {
          "name": "--bankai-code-block-line-height",
          "value": "1.6"
        },
        {
          "name": "--bankai-code-block-radius",
          "value": "var(--bankai-radius)"
        },
        {
          "name": "--bankai-code-block-padding-block",
          "value": "var(--bankai-space-8)"
        },
        {
          "name": "--bankai-code-block-padding-inline",
          "value": "var(--bankai-space-8)"
        },
        {
          "name": "--bankai-code-block-copy-offset",
          "value": "var(--bankai-space-4)"
        }
      ]
    }
  },
  "BankaiCode": {
    "props": [],
    "slots": [
      {
        "name": "default",
        "description": "Inline code content — an identifier, token, path, or short snippet."
      }
    ],
    "events": [],
    "exposed": [],
    "theming": {
      "bankai": [
        {
          "name": "--bankai-code-font-family",
          "value": "var(--bankai-font-mono)"
        },
        {
          "name": "--bankai-code-bg",
          "value": "var(--bankai-color-surface)"
        },
        {
          "name": "--bankai-code-radius",
          "value": "var(--bankai-radius)"
        },
        {
          "name": "--bankai-code-font-size",
          "value": "0.875em"
        },
        {
          "name": "--bankai-code-padding-block",
          "value": "0.125em"
        },
        {
          "name": "--bankai-code-padding-inline",
          "value": "0.25em"
        }
      ]
    }
  },
  "BankaiContainer": {
    "props": [
      {
        "name": "as",
        "type": "HTML tag name",
        "required": false,
        "description": "Element to render as. Polymorphic — any non-void HTML tag name.",
        "default": "'div'"
      },
      {
        "name": "fluid",
        "type": "boolean",
        "required": false,
        "description": "Fill the available width (edge-to-edge) instead of the centered max-width default. This is the \"bars left/right on huge viewports\" toggle — fluid removes the max-width cap so the container spans its parent, keeping only the inline gutter. Centered content already collapses to edge-to-edge on its own when the parent is narrower than the max-width; fluid opts out of the cap even when there *is* room for bars (full-bleed heroes, dashboards).",
        "default": "false"
      }
    ],
    "slots": [
      {
        "name": "default",
        "description": "Container children — the content whose width is constrained."
      }
    ],
    "events": [],
    "exposed": [],
    "theming": {
      "bankai": [
        {
          "name": "--bankai-container-max-width",
          "value": "80rem"
        },
        {
          "name": "--bankai-container-gutter",
          "value": "var(--bankai-space-8, 1rem)"
        }
      ]
    }
  },
  "BankaiFlex": {
    "props": [
      {
        "name": "as",
        "type": "HTML tag name",
        "required": false,
        "description": "Element to render as. Polymorphic — any HTML tag name.",
        "default": "'div'"
      },
      {
        "name": "direction",
        "type": "'row' | 'row-reverse' | 'column' | 'column-reverse'",
        "required": false,
        "description": "flex-direction. Omitted from the style when unset (browser default row applies)."
      },
      {
        "name": "align",
        "type": "'start' | 'end' | 'center' | 'baseline' | 'stretch' | (string)",
        "required": false,
        "description": "Cross-axis alignment (align-items). A short keyword (BankaiFlexAlign) reflects as data-bankai-align; any other string is a verbatim align-items value. Omitted when unset."
      },
      {
        "name": "justify",
        "type": "'start' | 'end' | 'center' | 'between' | 'around' | 'evenly' | (string)",
        "required": false,
        "description": "Main-axis distribution (justify-content). A short keyword (BankaiFlexJustify) reflects as data-bankai-justify; any other string is a verbatim justify-content value ('space-between', 'flex-start', 'var(--x)'). Omitted when unset."
      },
      {
        "name": "gap",
        "type": "'xs' | 'sm' | 'md' | 'lg' | 'xl' | number | string",
        "required": false,
        "description": "Spacing between children (gap). A named t-shirt step ('xs'–'xl', --bankai-gap-<name>) or a number/bare-numeric string (a rem-based --bankai-space-<n> step); any other string is a verbatim CSS length ('1rem', 'clamp(…)', 'var(--x)'). Omitted when unset."
      },
      {
        "name": "wrap",
        "type": "'nowrap' | 'wrap' | 'wrap-reverse'",
        "required": false,
        "description": "flex-wrap. Omitted when unset (browser default nowrap applies)."
      },
      {
        "name": "inline",
        "type": "boolean",
        "required": false,
        "description": "Render as inline-flex instead of flex.",
        "default": "false"
      }
    ],
    "slots": [
      {
        "name": "default",
        "description": "Flex children."
      }
    ],
    "events": [],
    "exposed": [],
    "theming": {
      "bankai": []
    }
  },
  "BankaiFooter": {
    "props": [],
    "slots": [
      {
        "name": "default",
        "description": "Footer content — typically copyright, secondary navigation, or site meta."
      }
    ],
    "events": [],
    "exposed": [],
    "theming": {
      "bankai": [
        {
          "name": "--bankai-footer-padding-block",
          "value": "var(--bankai-space-8)"
        },
        {
          "name": "--bankai-footer-padding-inline",
          "value": "var(--bankai-space-12)"
        },
        {
          "name": "--bankai-footer-border-width",
          "value": "1px"
        },
        {
          "name": "--bankai-footer-border-color",
          "value": "var(--bankai-color-border)"
        },
        {
          "name": "--bankai-footer-background",
          "value": "var(--bankai-color-bg)"
        }
      ]
    }
  },
  "BankaiGrid": {
    "props": [
      {
        "name": "as",
        "type": "HTML tag name",
        "required": false,
        "description": "Element to render as. Polymorphic — any HTML tag name.",
        "default": "'div'"
      },
      {
        "name": "columns",
        "type": "number | string",
        "required": false,
        "description": "grid-template-columns. A number (or a bare-numeric string like '3') is a count of equal repeat(<n>, minmax(0, 1fr)) tracks; any other string is a verbatim value ('200px 1fr', 'repeat(auto-fill, minmax(10rem, 1fr))'). Omitted when unset."
      },
      {
        "name": "rows",
        "type": "number | string",
        "required": false,
        "description": "grid-template-rows. A number (or a bare-numeric string) is a count of equal repeat(<n>, minmax(0, 1fr)) tracks; any other string is a verbatim value. Omitted when unset."
      },
      {
        "name": "areas",
        "type": "string | string[]",
        "required": false,
        "description": "grid-template-areas. A string array is auto-quoted per row (['a b', 'c d'] → \"a b\" \"c d\"); a string is used verbatim (must already carry its own quotes). Omitted when unset."
      },
      {
        "name": "gap",
        "type": "'xs' | 'sm' | 'md' | 'lg' | 'xl' | number | string",
        "required": false,
        "description": "Spacing between tracks (gap). A named t-shirt step ('xs'–'xl', --bankai-gap-<name>) or a number/bare-numeric string (a rem-based --bankai-space-<n> step); any other string is a verbatim CSS length ('1rem', '1rem 2rem', 'clamp(…)'). Omitted when unset."
      },
      {
        "name": "flow",
        "type": "'row' | 'column' | 'dense' | 'row-dense' | 'column-dense'",
        "required": false,
        "description": "grid-auto-flow — direction the grid auto-places items. Omitted when unset (browser default row)."
      },
      {
        "name": "align",
        "type": "'start' | 'end' | 'center' | 'baseline' | 'stretch' | (string)",
        "required": false,
        "description": "In-cell block-axis alignment (align-items). A native keyword (BankaiGridAlign) reflects as data-bankai-align; any other string is a verbatim align-items value. Omitted when unset."
      },
      {
        "name": "justify",
        "type": "'start' | 'end' | 'center' | 'stretch' | (string)",
        "required": false,
        "description": "In-cell inline-axis alignment (justify-items). A native keyword (BankaiGridJustify) reflects as data-bankai-justify; any other string is a verbatim justify-items value. Omitted when unset."
      },
      {
        "name": "inline",
        "type": "boolean",
        "required": false,
        "description": "Render as inline-grid instead of grid.",
        "default": "false"
      }
    ],
    "slots": [
      {
        "name": "default",
        "description": "Grid children."
      }
    ],
    "events": [],
    "exposed": [],
    "theming": {
      "bankai": []
    }
  },
  "BankaiHeader": {
    "props": [],
    "slots": [
      {
        "name": "default",
        "description": "Header content — typically a BankaiNavbar (brand + links + actions)."
      }
    ],
    "events": [],
    "exposed": [],
    "theming": {
      "bankai": [
        {
          "name": "--bankai-header-padding-block",
          "value": "var(--bankai-space-8)"
        },
        {
          "name": "--bankai-header-padding-inline",
          "value": "var(--bankai-space-12)"
        },
        {
          "name": "--bankai-header-border-width",
          "value": "1px"
        },
        {
          "name": "--bankai-header-border-color",
          "value": "var(--bankai-color-border)"
        },
        {
          "name": "--bankai-header-background",
          "value": "var(--bankai-color-bg)"
        }
      ]
    }
  },
  "BankaiHeading": {
    "props": [
      {
        "name": "level",
        "type": "1 | 2 | 3 | 4 | 5 | 6",
        "required": true,
        "description": "Heading level 1–6 → renders the native <h1>–<h6> and reflects data-bankai-level. Required — there is no safe default heading level, and a wrong one breaks the document outline assistive tech navigates by, so the level is always an explicit, deliberate choice."
      }
    ],
    "slots": [
      {
        "name": "default",
        "description": "Heading content."
      }
    ],
    "events": [],
    "exposed": [],
    "theming": {
      "bankai": [
        {
          "name": "--bankai-heading-color",
          "value": "var(--bankai-color-fg)"
        },
        {
          "name": "--bankai-heading-font-weight",
          "value": "600"
        },
        {
          "name": "--bankai-heading-size-1",
          "value": "2.25rem"
        },
        {
          "name": "--bankai-heading-line-height-1",
          "value": "2.5rem"
        },
        {
          "name": "--bankai-heading-size-2",
          "value": "1.875rem"
        },
        {
          "name": "--bankai-heading-line-height-2",
          "value": "2.25rem"
        },
        {
          "name": "--bankai-heading-size-3",
          "value": "1.5rem"
        },
        {
          "name": "--bankai-heading-line-height-3",
          "value": "2rem"
        },
        {
          "name": "--bankai-heading-size-4",
          "value": "1.25rem"
        },
        {
          "name": "--bankai-heading-line-height-4",
          "value": "1.75rem"
        },
        {
          "name": "--bankai-heading-size-5",
          "value": "1.125rem"
        },
        {
          "name": "--bankai-heading-line-height-5",
          "value": "1.75rem"
        },
        {
          "name": "--bankai-heading-size-6",
          "value": "1rem"
        },
        {
          "name": "--bankai-heading-line-height-6",
          "value": "1.5rem"
        }
      ]
    }
  },
  "BankaiIcon": {
    "props": [
      {
        "name": "as",
        "type": "BankaiIconElement | string",
        "required": false,
        "description": "Element to render as. Polymorphic — suggests BankaiIconElement ('span' / 'i'); any tag string is also accepted.",
        "default": "'span'"
      },
      {
        "name": "name",
        "type": "string",
        "required": false,
        "description": "Icon token, applied as a class on the root — the ergonomic, reactive counterpart to writing the class yourself. With no resolver it is applied verbatim (so name=\"i-mdi-home\" works out of the box for UnoCSS / Iconify-CSS); set config.icon.class to map a bare token (e.g. 'mdi:home') to your setup's class. Omit it and use the default slot for an inline <svg> / icon component instead."
      },
      {
        "name": "size",
        "type": "'xs' | 'sm' | 'md' | 'lg' | 'xl' | string",
        "required": false,
        "description": "Icon size. A named xs–xl step (--bankai-icon-size-*) reflects as data-bankai-size; any other string is a verbatim CSS font-size driving the 1em box. Omitted when unset (inherits the ambient font size, so the icon matches surrounding text)."
      },
      {
        "name": "label",
        "type": "string",
        "required": false,
        "description": "Accessible name for a MEANINGFUL icon: sets role=\"img\" + aria-label, so assistive tech announces it. Leave unset for a DECORATIVE icon — the default — and the root is hidden from assistive tech with aria-hidden (unless you supply your own aria-label/aria-labelledby/title/role=\"img\")."
      },
      {
        "name": "no-square",
        "type": "boolean",
        "required": false,
        "description": "Opt out of the default 1:1 (square) box and let the icon keep its own aspect ratio (height driven by size, width intrinsic). By default the root is a square box and non-square content is centered and contained (letterboxed) rather than distorted. Reflected as data-bankai-square=\"false\" when set.",
        "default": "false"
      }
    ],
    "slots": [
      {
        "name": "default",
        "description": "The icon markup — an inline <svg>, a third-party icon component (e.g. Iconify's <Icon> / <iconify-icon>), an <img>, or an SVG sprite <use>. The wrapper adds the box + a11y around it."
      }
    ],
    "events": [],
    "exposed": [],
    "theming": {
      "bankai": [
        {
          "name": "--bankai-icon-size-xs",
          "value": "0.75rem"
        },
        {
          "name": "--bankai-icon-size-sm",
          "value": "1rem"
        },
        {
          "name": "--bankai-icon-size-md",
          "value": "1.25rem"
        },
        {
          "name": "--bankai-icon-size-lg",
          "value": "1.5rem"
        },
        {
          "name": "--bankai-icon-size-xl",
          "value": "2rem"
        }
      ]
    }
  },
  "BankaiInputNumber": {
    "props": [
      {
        "name": "min",
        "type": "number",
        "required": false,
        "description": "Minimum value, set as the native min attribute — the platform clamps stepping and flags out-of-range values. Also disables the decrement control once the value reaches it."
      },
      {
        "name": "max",
        "type": "number",
        "required": false,
        "description": "Maximum value, set as the native max attribute — the platform clamps stepping and flags out-of-range values. Also disables the increment control once the value reaches it."
      },
      {
        "name": "step",
        "type": "number",
        "required": false,
        "description": "Step granularity, set as the native step attribute — the amount each stepper control and each arrow-key press changes the value by, and the allowed value increments. Also drives the default inputmode (integer → 'numeric', fractional → 'decimal').",
        "default": "1"
      },
      {
        "name": "size",
        "type": "'sm' | 'md' | 'lg' | (string)",
        "required": false,
        "description": "Size scale, forwarded to the field and reflected as data-bankai-size. A named step (sm/md/lg) is themed; any other string reflects verbatim as an escape hatch.",
        "default": "'md'"
      },
      {
        "name": "disabled",
        "type": "boolean",
        "required": false,
        "description": "Disable the control via the native disabled attribute (also disables both stepper controls).",
        "default": "false"
      },
      {
        "name": "readonly",
        "type": "boolean",
        "required": false,
        "description": "Make the control read-only via the native readonly attribute — the value shows and can be selected/copied but not edited, and both stepper controls are disabled. Unlike disabled, it still submits with a form.",
        "default": "false"
      },
      {
        "name": "buttons",
        "type": "boolean | 'stacked' | 'split' | (string)",
        "required": false,
        "description": "The stepper controls. false (default) renders just the bare <input> — no wrapper, no controls (keyboard/arrow-key stepping still works). true renders the controls in the default 'stacked' layout; a BankaiInputNumberButtons string ('stacked'/'split' or a custom value) picks the layout explicitly. Any truthy value wraps the field in a <div class=\"bankai-input-number\"> and reflects the resolved layout as data-bankai-buttons.",
        "default": "false"
      },
      {
        "name": "inputmode",
        "type": "'numeric' | 'decimal' | (string)",
        "required": false,
        "description": "Mobile keyboard hint, set as the native inputmode attribute. Defaults smartly from step ('numeric' for an integer step, 'decimal' otherwise); set explicitly to override."
      },
      {
        "name": "model-value",
        "type": "number",
        "required": false,
        "description": "The numeric value, bound with v-model — number | undefined (see BankaiInputNumberModelValue): undefined while unset and whenever the field is empty or holds an incomplete/invalid entry. Never coerced to 0, so a wrapping field/validation layer can tell \"no number yet\" from an entered value."
      }
    ],
    "slots": [
      {
        "name": "decrement",
        "description": "Content of the decrement control (defaults to a minus glyph). Swap in an icon (e.g. BankaiIcon). Only rendered when buttons is truthy; the control is aria-hidden, so slot content is not announced."
      },
      {
        "name": "increment",
        "description": "Content of the increment control (defaults to a plus glyph). Swap in an icon (e.g. BankaiIcon). Only rendered when buttons is truthy; the control is aria-hidden, so slot content is not announced."
      }
    ],
    "events": [
      {
        "name": "update:model-value",
        "type": "[value: number | undefined]",
        "description": ""
      }
    ],
    "exposed": [
      {
        "name": "el",
        "type": "HTMLInputElement | null",
        "description": "The underlying native <input type=\"number\"> element, or null before mount / after unmount."
      },
      {
        "name": "focus",
        "type": "(options?: FocusOptions | undefined) => void",
        "description": "Focus the input."
      },
      {
        "name": "blur",
        "type": "() => void",
        "description": "Remove focus from the input."
      },
      {
        "name": "select",
        "type": "() => void",
        "description": "Select the input's text."
      },
      {
        "name": "stepUp",
        "type": "(count?: number | undefined) => void",
        "description": "Increment the value by count steps (delegates to the native HTMLInputElement.stepUp, so it honors min/max/step). No-op while disabled/readonly."
      },
      {
        "name": "stepDown",
        "type": "(count?: number | undefined) => void",
        "description": "Decrement the value by count steps (delegates to the native HTMLInputElement.stepDown). No-op while disabled/readonly."
      }
    ],
    "theming": {
      "bankai": [
        {
          "name": "--bankai-input-number-radius",
          "value": "var(--bankai-input-radius, var(--bankai-radius))"
        },
        {
          "name": "--bankai-input-number-control-inline-size",
          "value": "2.25rem"
        },
        {
          "name": "--bankai-input-number-control-bg",
          "value": "var(--bankai-color-surface)"
        },
        {
          "name": "--bankai-input-number-control-fg",
          "value": "var(--bankai-color-fg)"
        },
        {
          "name": "--bankai-input-number-control-border-width",
          "value": "var(--bankai-input-border-width, 1px)"
        },
        {
          "name": "--bankai-input-number-control-border-color",
          "value": "var( --bankai-input-border-color, var(--bankai-color-border) )"
        },
        {
          "name": "--bankai-input-number-control-font-size",
          "value": "var(--bankai-text-size-md)"
        },
        {
          "name": "--bankai-input-number-control-hover-bg",
          "value": "var(--bankai-color-bg)"
        },
        {
          "name": "--bankai-input-number-control-disabled-opacity",
          "value": "0.5"
        },
        {
          "name": "--bankai-input-number-control-disabled-cursor",
          "value": "not-allowed"
        },
        {
          "name": "--bankai-input-number-control-transition",
          "value": "color 150ms ease, background-color 150ms ease"
        }
      ]
    }
  },
  "BankaiInputPassword": {
    "props": [
      {
        "name": "size",
        "type": "'sm' | 'md' | 'lg' | (string)",
        "required": false,
        "description": "Size scale, forwarded to the field and reflected as data-bankai-size. A named step (sm/md/lg) is themed; any other string reflects verbatim as an escape hatch.",
        "default": "'md'"
      },
      {
        "name": "disabled",
        "type": "boolean",
        "required": false,
        "description": "Disable the control via the native disabled attribute (also disables the reveal button).",
        "default": "false"
      },
      {
        "name": "readonly",
        "type": "boolean",
        "required": false,
        "description": "Make the control read-only via the native readonly attribute — the value shows and can be selected/copied but not edited (the reveal button still works). Unlike disabled, it still submits with a form.",
        "default": "false"
      },
      {
        "name": "toggle",
        "type": "boolean",
        "required": false,
        "description": "Render the built-in reveal toggle. true (default) wraps the field in a <div class=\"bankai-input-password\"> and adds a reveal <button data-part=\"toggle\">. false renders just the bare <input> with no wrapper or button — revealing then requires driving v-model:revealed from a consumer control (the reveal still flips the input type). The reveal state itself is v-model:revealed, independent of this prop.",
        "default": "true"
      },
      {
        "name": "show-label",
        "type": "string",
        "required": false,
        "description": "The reveal button's accessible name (and its visible label, when the toggle slot is not used) while the password is masked — activating it reveals the value. Overrides the resolved inputPassword.show message for this instance; unset, it resolves through the global i18n config (BankaiI18nConfig ), defaulting to the English 'Show password'."
      },
      {
        "name": "hide-label",
        "type": "string",
        "required": false,
        "description": "The reveal button's accessible name (and its visible label, when the toggle slot is not used) while the value is revealed — activating it masks the value again. Overrides the resolved inputPassword.hide message for this instance; unset, it resolves through the global i18n config (BankaiI18nConfig ), defaulting to the English 'Hide password'."
      },
      {
        "name": "model-value",
        "type": "string",
        "required": false,
        "description": "The password value, bound with the default v-model — string | undefined (see BankaiInputPasswordModelValue): a string once set, undefined while unset."
      },
      {
        "name": "revealed",
        "type": "boolean",
        "required": false,
        "description": "Whether the value is revealed, bound with v-model:revealed (default false). Drives the input type (text when revealed, password when masked) and the reveal button's label/state — independent of the toggle prop, so a consumer can drive it from their own control even with the built-in button off.",
        "default": "false"
      }
    ],
    "slots": [
      {
        "name": "toggle",
        "description": "Content of the reveal button (defaults to the current showLabel / hideLabel text). Receives the current revealed state so a consumer can swap the icon/label (e.g. an eye ↔ eye-off BankaiIcon). The button keeps its accessible name from the labels regardless of what this slot renders. Only rendered when toggle is true."
      }
    ],
    "events": [
      {
        "name": "update:model-value",
        "type": "[value: string | undefined]",
        "description": ""
      },
      {
        "name": "update:revealed",
        "type": "[value: boolean]",
        "description": ""
      }
    ],
    "exposed": [
      {
        "name": "el",
        "type": "HTMLInputElement | null",
        "description": "The underlying native <input> element, or null before mount / after unmount."
      },
      {
        "name": "focus",
        "type": "(options?: FocusOptions | undefined) => void",
        "description": "Focus the input (delegates to the native HTMLInputElement.focus)."
      },
      {
        "name": "blur",
        "type": "() => void",
        "description": "Remove focus from the input (delegates to the native HTMLInputElement.blur)."
      },
      {
        "name": "select",
        "type": "() => void",
        "description": "Select all editable text in the input (delegates to the native HTMLInputElement.select)."
      }
    ],
    "theming": {
      "bankai": [
        {
          "name": "--bankai-input-password-radius",
          "value": "var(--bankai-input-radius, var(--bankai-radius))"
        },
        {
          "name": "--bankai-input-password-toggle-padding-inline",
          "value": "var(--bankai-space-4)"
        },
        {
          "name": "--bankai-input-password-toggle-bg",
          "value": "var(--bankai-color-surface)"
        },
        {
          "name": "--bankai-input-password-toggle-fg",
          "value": "var(--bankai-color-fg)"
        },
        {
          "name": "--bankai-input-password-toggle-border-width",
          "value": "var(--bankai-input-border-width, 1px)"
        },
        {
          "name": "--bankai-input-password-toggle-border-color",
          "value": "var( --bankai-input-border-color, var(--bankai-color-border) )"
        },
        {
          "name": "--bankai-input-password-toggle-font-size",
          "value": "var(--bankai-text-size-sm)"
        },
        {
          "name": "--bankai-input-password-toggle-hover-bg",
          "value": "var(--bankai-color-bg)"
        },
        {
          "name": "--bankai-input-password-toggle-disabled-opacity",
          "value": "0.5"
        },
        {
          "name": "--bankai-input-password-toggle-disabled-cursor",
          "value": "not-allowed"
        },
        {
          "name": "--bankai-input-password-toggle-transition",
          "value": "color 150ms ease, background-color 150ms ease"
        }
      ]
    }
  },
  "BankaiInput": {
    "props": [
      {
        "name": "type",
        "type": "'text' | 'email' | 'search' | 'tel' | 'url' | (string)",
        "required": false,
        "description": "Native input type. A named text step (text/email/search/tel/url) is what this component is for; any other string still passes through. Behavior-rich types have dedicated components (BankaiInputNumber, BankaiInputPassword).",
        "default": "'text'"
      },
      {
        "name": "size",
        "type": "'sm' | 'md' | 'lg' | (string)",
        "required": false,
        "description": "Size scale. A named step (sm/md/lg) is themed; any other string reflects verbatim as data-bankai-size as an escape hatch for a custom consumer-styled size.",
        "default": "'md'"
      },
      {
        "name": "disabled",
        "type": "boolean",
        "required": false,
        "description": "Disable the input via the native disabled attribute.",
        "default": "false"
      },
      {
        "name": "readonly",
        "type": "boolean",
        "required": false,
        "description": "Make the input read-only via the native readonly attribute — the value shows and can be selected/copied but not edited (and, unlike disabled, it still submits with a form).",
        "default": "false"
      },
      {
        "name": "model-value",
        "type": "string",
        "required": false,
        "description": "The input's value, bound with v-model — string | undefined (see BankaiInputModelValue): a string once set, undefined while unset. An unset model is never coerced to '', which preserves the \"never entered\" vs \"entered then cleared\" distinction a future field/validation layer relies on."
      }
    ],
    "slots": [],
    "events": [
      {
        "name": "update:model-value",
        "type": "[value: string | undefined]",
        "description": ""
      }
    ],
    "exposed": [
      {
        "name": "el",
        "type": "HTMLInputElement | null",
        "description": "The underlying native <input> element, or null before mount / after unmount."
      },
      {
        "name": "focus",
        "type": "(options?: FocusOptions | undefined) => void",
        "description": "Focus the input (delegates to the native HTMLInputElement.focus)."
      },
      {
        "name": "blur",
        "type": "() => void",
        "description": "Remove focus from the input (delegates to the native HTMLInputElement.blur)."
      },
      {
        "name": "select",
        "type": "() => void",
        "description": "Select all editable text in the input (delegates to the native HTMLInputElement.select)."
      }
    ],
    "theming": {
      "bankai": [
        {
          "name": "--bankai-input-fg",
          "value": "var(--bankai-color-fg)"
        },
        {
          "name": "--bankai-input-bg",
          "value": "var(--bankai-color-bg)"
        },
        {
          "name": "--bankai-input-placeholder-color",
          "value": "var(--bankai-color-fg-subtle)"
        },
        {
          "name": "--bankai-input-border-width",
          "value": "1px"
        },
        {
          "name": "--bankai-input-border-style",
          "value": "solid"
        },
        {
          "name": "--bankai-input-border-color",
          "value": "var(--bankai-color-border)"
        },
        {
          "name": "--bankai-input-radius",
          "value": "var(--bankai-radius)"
        },
        {
          "name": "--bankai-input-inline-size",
          "value": "100%"
        },
        {
          "name": "--bankai-input-font",
          "value": "inherit"
        },
        {
          "name": "--bankai-input-transition",
          "value": "color 150ms ease, background-color 150ms ease, border-color 150ms ease"
        },
        {
          "name": "--bankai-input-focus-ring",
          "value": "var(--bankai-focus-ring)"
        },
        {
          "name": "--bankai-input-focus-border-color",
          "value": "var(--bankai-color-accent)"
        },
        {
          "name": "--bankai-input-focus-outline-width",
          "value": "2px"
        },
        {
          "name": "--bankai-input-focus-outline-offset",
          "value": "2px"
        },
        {
          "name": "--bankai-input-readonly-bg",
          "value": "var(--bankai-color-surface)"
        },
        {
          "name": "--bankai-input-disabled-opacity",
          "value": "0.5"
        },
        {
          "name": "--bankai-input-disabled-cursor",
          "value": "not-allowed"
        },
        {
          "name": "--bankai-input-sm-padding-y",
          "value": "var(--bankai-space-1)"
        },
        {
          "name": "--bankai-input-sm-padding-x",
          "value": "var(--bankai-space-4)"
        },
        {
          "name": "--bankai-input-sm-font-size",
          "value": "var(--bankai-text-size-sm)"
        },
        {
          "name": "--bankai-input-md-padding-y",
          "value": "var(--bankai-space-3)"
        },
        {
          "name": "--bankai-input-md-padding-x",
          "value": "var(--bankai-space-6)"
        },
        {
          "name": "--bankai-input-md-font-size",
          "value": "var(--bankai-text-size-md)"
        },
        {
          "name": "--bankai-input-lg-padding-y",
          "value": "var(--bankai-space-4)"
        },
        {
          "name": "--bankai-input-lg-padding-x",
          "value": "var(--bankai-space-8)"
        },
        {
          "name": "--bankai-input-lg-font-size",
          "value": "var(--bankai-text-size-lg)"
        }
      ]
    }
  },
  "BankaiLayout": {
    "props": [],
    "slots": [
      {
        "name": "header",
        "description": "Top region — wrapped in a BankaiHeader (<header class=\"bankai-header\">, the banner landmark). Typically holds a navbar. Omitted from the DOM when not provided."
      },
      {
        "name": "sidebar",
        "description": "Side region — wrapped in a BankaiAside (<aside class=\"bankai-aside\">, the complementary landmark). Typically holds a sidebar nav. Omitted from the DOM when not provided."
      },
      {
        "name": "footer",
        "description": "Bottom region — wrapped in a BankaiFooter (<footer class=\"bankai-footer\">, the contentinfo landmark). Omitted from the DOM when not provided."
      },
      {
        "name": "default",
        "description": "Main content region — wrapped in a BankaiMain (<main class=\"bankai-main\">, the main landmark), always rendered. The per-route host (BankaiPage) and content go here; nothing inside should render its own <main> (landmark uniqueness)."
      }
    ],
    "events": [],
    "exposed": [],
    "theming": {
      "bankai": [
        {
          "name": "--bankai-layout-min-block-size",
          "value": "100dvh"
        },
        {
          "name": "--bankai-layout-columns",
          "value": "auto 1fr"
        },
        {
          "name": "--bankai-layout-rows",
          "value": "auto 1fr auto"
        },
        {
          "name": "--bankai-layout-areas",
          "value": "'header header' 'sidebar main' 'footer footer'"
        }
      ]
    }
  },
  "BankaiLink": {
    "props": [
      {
        "name": "external",
        "type": "boolean",
        "required": false,
        "description": "Force a plain <a> even when to is set and a router is available — e.g. to leave the SPA for a full-page navigation. Also marks the link external via data-bankai-external (independent of the router path), so it works alongside either to or href. A full-page navigation needs a URL, so pair external with a string to (or an href); an object to has none and renders a dead <a> (warns in dev).",
        "default": "false"
      },
      {
        "name": "to",
        "type": "RouteLocationRaw | string | object",
        "required": false,
        "description": "Internal navigation target, handed to the resolved router link (NuxtLink, else RouterLink). When no router is installed, a string to degrades to a plain <a :href>; an object to needs a router (there is nothing sensible to put in href without one). An object to with no router to resolve it — including when external forces a plain <a> — renders a destination-less anchor and warns in dev; pass a string to/href, or install a router. Its type is a router-agnostic fallback by default and vue-router's RouteLocationRaw once the @bankai-vue/core/vue-router types augmentation is active — see BankaiLinkTo."
      },
      {
        "name": "href",
        "type": "string",
        "required": false,
        "description": "Explicit anchor target. Always renders a native <a href>, never a router link — use it for external URLs, mailto:/tel:, fragments, and downloads."
      }
    ],
    "slots": [
      {
        "name": "default",
        "description": "Link content — the label, and optionally an icon."
      }
    ],
    "events": [],
    "exposed": [],
    "theming": {
      "bankai": [
        {
          "name": "--bankai-link-color",
          "value": "var(--bankai-color-accent)"
        },
        {
          "name": "--bankai-link-color-hover",
          "value": "color-mix(in oklch, var(--bankai-link-color), black 15%)"
        },
        {
          "name": "--bankai-link-color-active",
          "value": "color-mix(in oklch, var(--bankai-link-color), black 25%)"
        },
        {
          "name": "--bankai-link-decoration",
          "value": "underline"
        },
        {
          "name": "--bankai-link-decoration-hover",
          "value": "underline"
        },
        {
          "name": "--bankai-link-underline-offset",
          "value": "0.15em"
        },
        {
          "name": "--bankai-link-cursor",
          "value": "pointer"
        },
        {
          "name": "--bankai-link-transition",
          "value": "color 150ms ease, text-decoration-color 150ms ease"
        },
        {
          "name": "--bankai-link-focus-ring",
          "value": "var(--bankai-focus-ring)"
        },
        {
          "name": "--bankai-link-focus-outline-width",
          "value": "2px"
        },
        {
          "name": "--bankai-link-focus-outline-offset",
          "value": "2px"
        },
        {
          "name": "--bankai-link-focus-radius",
          "value": "var(--bankai-radius)"
        }
      ]
    }
  },
  "BankaiMain": {
    "props": [],
    "slots": [
      {
        "name": "default",
        "description": "The document's primary content — typically a BankaiPage / BankaiContainer and the page body."
      }
    ],
    "events": [],
    "exposed": [],
    "theming": {
      "bankai": []
    }
  },
  "BankaiPage": {
    "props": [],
    "slots": [
      {
        "name": "default",
        "description": "The route's content — typically a BankaiContainer (or several, at different widths) and the page body."
      }
    ],
    "events": [],
    "exposed": [],
    "theming": {
      "bankai": [
        {
          "name": "--bankai-page-min-block-size",
          "value": "100%"
        }
      ]
    }
  },
  "BankaiText": {
    "props": [
      {
        "name": "as",
        "type": "BankaiTextElement | string",
        "required": false,
        "description": "Element to render as. Polymorphic — suggests the phrasing/text elements (BankaiTextElement); any tag string (e.g. a custom element) is also accepted. Use an inline-semantic element ('strong', 'em', 'mark', 'code', 'kbd', 'del', …) to carry that meaning natively.",
        "default": "'span'"
      },
      {
        "name": "size",
        "type": "'xs' | 'sm' | 'md' | 'lg' | 'xl' | '2xl' | string",
        "required": false,
        "description": "Type size. A named xs–2xl step (--bankai-text-size-*) reflects as data-bankai-size; any other string is a verbatim CSS font-size. Omitted when unset (inherits the ambient font size)."
      },
      {
        "name": "weight",
        "type": "'thin' … 'black' | number | string",
        "required": false,
        "description": "Font weight. A named step (BankaiTextWeight) reflects as data-bankai-weight; a number or any other string ('var(--wght)', 'calc(…)', 'lighter') is a verbatim font-weight — a variable font renders a numeric value along its wght axis. Omitted when unset (inherits the ambient weight)."
      },
      {
        "name": "tone",
        "type": "'default' | 'muted' | 'subtle' | string",
        "required": false,
        "description": "Text tone. A named neutral tone reflects as data-bankai-tone; any other string is a verbatim CSS color. Omitted when unset (inherits the ambient color)."
      },
      {
        "name": "truncate",
        "type": "boolean",
        "required": false,
        "description": "Truncate overflowing text to a single line with an ellipsis. Reflected on the root as data-bankai-truncate. The theme rule makes the element block-level, so it truncates against the available width.",
        "default": "false"
      }
    ],
    "slots": [
      {
        "name": "default",
        "description": "Text content."
      }
    ],
    "events": [],
    "exposed": [],
    "theming": {
      "bankai": [
        {
          "name": "--bankai-text-color",
          "value": "var(--bankai-color-fg)"
        },
        {
          "name": "--bankai-text-color-muted",
          "value": "var(--bankai-color-fg-muted)"
        },
        {
          "name": "--bankai-text-color-subtle",
          "value": "var(--bankai-color-fg-subtle)"
        },
        {
          "name": "--bankai-text-line-height-xs",
          "value": "1rem"
        },
        {
          "name": "--bankai-text-line-height-sm",
          "value": "1.25rem"
        },
        {
          "name": "--bankai-text-line-height-md",
          "value": "1.5rem"
        },
        {
          "name": "--bankai-text-line-height-lg",
          "value": "1.75rem"
        },
        {
          "name": "--bankai-text-line-height-xl",
          "value": "1.75rem"
        },
        {
          "name": "--bankai-text-line-height-2xl",
          "value": "2rem"
        }
      ]
    }
  }
} satisfies Record<string, ComponentMeta>;
