// AUTO-GENERATED by scripts/generate-component-meta.ts — do not edit by hand.
// Regenerate with `pnpm docs:meta`. Props/slots/events, defaults, and descriptions come from
// @bankai-vue/core's source SFCs; the `type` column merges auto types with curated overrides.
// This file is excluded from oxfmt so the `--check` staleness comparison stays byte-exact.
/* eslint-disable */

export interface MetaProp {
  name: string;
  type: string;
  default?: string;
  required: boolean;
  description: string;
}

export interface MetaSlot {
  name: string;
  description: string;
}

export interface MetaEvent {
  name: string;
  type: string;
  description: string;
}

export interface ComponentMeta {
  props: MetaProp[];
  slots: MetaSlot[];
  events: MetaEvent[];
}

export const componentMeta = {
  "BankaiButton": {
    "props": [
      {
        "name": "variant",
        "type": "'solid' | 'outline' | 'ghost' | (string)",
        "required": false,
        "description": "Visual variant. A named house variant (solid/outline/ghost) is themed; any other string reflects verbatim as data-bankai-variant as an escape hatch for a custom consumer-styled variant.",
        "default": "'solid'"
      },
      {
        "name": "size",
        "type": "'sm' | 'md' | 'lg' | (string)",
        "required": false,
        "description": "Size scale. A named step (sm/md/lg) is themed; any other string reflects verbatim as data-bankai-size as an escape hatch for a custom consumer-styled size.",
        "default": "'md'"
      },
      {
        "name": "type",
        "type": "'submit' | 'reset' | 'button'",
        "required": false,
        "description": "Native button type. Defaults to 'button' rather than the HTML default 'submit', so the button never submits a surrounding form by accident.",
        "default": "'button'"
      },
      {
        "name": "disabled",
        "type": "boolean",
        "required": false,
        "description": "Disable the button via the native disabled attribute.",
        "default": "false"
      }
    ],
    "slots": [
      {
        "name": "default",
        "description": "Button content — label and/or icons."
      }
    ],
    "events": []
  },
  "BankaiCode": {
    "props": [],
    "slots": [
      {
        "name": "default",
        "description": "Inline code content — an identifier, token, path, or short snippet."
      }
    ],
    "events": []
  },
  "BankaiContainer": {
    "props": [
      {
        "name": "as",
        "type": "HTML tag name",
        "required": false,
        "description": "Element to render as. Polymorphic — any non-void HTML tag name.",
        "default": "'div'"
      },
      {
        "name": "fluid",
        "type": "boolean",
        "required": false,
        "description": "Fill the available width (edge-to-edge) instead of the centered max-width default. This is the \"bars left/right on huge viewports\" toggle — fluid removes the max-width cap so the container spans its parent, keeping only the inline gutter. Centered content already collapses to edge-to-edge on its own when the parent is narrower than the max-width; fluid opts out of the cap even when there *is* room for bars (full-bleed heroes, dashboards).",
        "default": "false"
      }
    ],
    "slots": [
      {
        "name": "default",
        "description": "Container children — the content whose width is constrained."
      }
    ],
    "events": []
  },
  "BankaiFlex": {
    "props": [
      {
        "name": "as",
        "type": "HTML tag name",
        "required": false,
        "description": "Element to render as. Polymorphic — any HTML tag name.",
        "default": "'div'"
      },
      {
        "name": "direction",
        "type": "'row' | 'row-reverse' | 'column' | 'column-reverse'",
        "required": false,
        "description": "flex-direction. Omitted from the style when unset (browser default row applies)."
      },
      {
        "name": "align",
        "type": "'start' | 'end' | 'center' | 'baseline' | 'stretch' | (string)",
        "required": false,
        "description": "Cross-axis alignment (align-items). A short keyword (BankaiFlexAlign) reflects as data-bankai-align; any other string is a verbatim align-items value. Omitted when unset."
      },
      {
        "name": "justify",
        "type": "'start' | 'end' | 'center' | 'between' | 'around' | 'evenly' | (string)",
        "required": false,
        "description": "Main-axis distribution (justify-content). A short keyword (BankaiFlexJustify) reflects as data-bankai-justify; any other string is a verbatim justify-content value ('space-between', 'flex-start', 'var(--x)'). Omitted when unset."
      },
      {
        "name": "gap",
        "type": "'xs' | 'sm' | 'md' | 'lg' | 'xl' | number | string",
        "required": false,
        "description": "Spacing between children (gap). A named t-shirt step ('xs'–'xl', --bankai-gap-<name>) or a number/bare-numeric string (a rem-based --bankai-space-<n> step); any other string is a verbatim CSS length ('1rem', 'clamp(…)', 'var(--x)'). Omitted when unset."
      },
      {
        "name": "wrap",
        "type": "'nowrap' | 'wrap' | 'wrap-reverse'",
        "required": false,
        "description": "flex-wrap. Omitted when unset (browser default nowrap applies)."
      },
      {
        "name": "inline",
        "type": "boolean",
        "required": false,
        "description": "Render as inline-flex instead of flex.",
        "default": "false"
      }
    ],
    "slots": [
      {
        "name": "default",
        "description": "Flex children."
      }
    ],
    "events": []
  },
  "BankaiGrid": {
    "props": [
      {
        "name": "as",
        "type": "HTML tag name",
        "required": false,
        "description": "Element to render as. Polymorphic — any HTML tag name.",
        "default": "'div'"
      },
      {
        "name": "columns",
        "type": "number | string",
        "required": false,
        "description": "grid-template-columns. A number (or a bare-numeric string like '3') is a count of equal repeat(<n>, minmax(0, 1fr)) tracks; any other string is a verbatim value ('200px 1fr', 'repeat(auto-fill, minmax(10rem, 1fr))'). Omitted when unset."
      },
      {
        "name": "rows",
        "type": "number | string",
        "required": false,
        "description": "grid-template-rows. A number (or a bare-numeric string) is a count of equal repeat(<n>, minmax(0, 1fr)) tracks; any other string is a verbatim value. Omitted when unset."
      },
      {
        "name": "areas",
        "type": "string | string[]",
        "required": false,
        "description": "grid-template-areas. A string array is auto-quoted per row (['a b', 'c d'] → \"a b\" \"c d\"); a string is used verbatim (must already carry its own quotes). Omitted when unset."
      },
      {
        "name": "gap",
        "type": "'xs' | 'sm' | 'md' | 'lg' | 'xl' | number | string",
        "required": false,
        "description": "Spacing between tracks (gap). A named t-shirt step ('xs'–'xl', --bankai-gap-<name>) or a number/bare-numeric string (a rem-based --bankai-space-<n> step); any other string is a verbatim CSS length ('1rem', '1rem 2rem', 'clamp(…)'). Omitted when unset."
      },
      {
        "name": "flow",
        "type": "'row' | 'column' | 'dense' | 'row-dense' | 'column-dense'",
        "required": false,
        "description": "grid-auto-flow — direction the grid auto-places items. Omitted when unset (browser default row)."
      },
      {
        "name": "align",
        "type": "'start' | 'end' | 'center' | 'baseline' | 'stretch' | (string)",
        "required": false,
        "description": "In-cell block-axis alignment (align-items). A native keyword (BankaiGridAlign) reflects as data-bankai-align; any other string is a verbatim align-items value. Omitted when unset."
      },
      {
        "name": "justify",
        "type": "'start' | 'end' | 'center' | 'stretch' | (string)",
        "required": false,
        "description": "In-cell inline-axis alignment (justify-items). A native keyword (BankaiGridJustify) reflects as data-bankai-justify; any other string is a verbatim justify-items value. Omitted when unset."
      },
      {
        "name": "inline",
        "type": "boolean",
        "required": false,
        "description": "Render as inline-grid instead of grid.",
        "default": "false"
      }
    ],
    "slots": [
      {
        "name": "default",
        "description": "Grid children."
      }
    ],
    "events": []
  },
  "BankaiHeading": {
    "props": [
      {
        "name": "level",
        "type": "1 | 2 | 3 | 4 | 5 | 6",
        "required": true,
        "description": "Heading level 1–6 → renders the native <h1>–<h6> and reflects data-bankai-level. Required — there is no safe default heading level, and a wrong one breaks the document outline assistive tech navigates by, so the level is always an explicit, deliberate choice."
      }
    ],
    "slots": [
      {
        "name": "default",
        "description": "Heading content."
      }
    ],
    "events": []
  },
  "BankaiLayout": {
    "props": [],
    "slots": [
      {
        "name": "header",
        "description": "Top region — wrapped in <header data-part=\"header\"> (the banner landmark). Typically holds a navbar. Omitted from the DOM when not provided."
      },
      {
        "name": "sidebar",
        "description": "Side region — wrapped in <aside data-part=\"sidebar\"> (the complementary landmark). Typically holds a sidebar nav. Omitted from the DOM when not provided."
      },
      {
        "name": "footer",
        "description": "Bottom region — wrapped in <footer data-part=\"footer\"> (the contentinfo landmark). Omitted from the DOM when not provided."
      },
      {
        "name": "default",
        "description": "Main content region — wrapped in <main data-part=\"main\"> (the main landmark), always rendered. The per-route host (BankaiPage) and content go here; nothing inside should render its own <main> (landmark uniqueness)."
      }
    ],
    "events": []
  },
  "BankaiLink": {
    "props": [
      {
        "name": "external",
        "type": "boolean",
        "required": false,
        "description": "Force a plain <a> even when to is set and a router is available — e.g. to leave the SPA for a full-page navigation. Also marks the link external via data-bankai-external (independent of the router path), so it works alongside either to or href. A full-page navigation needs a URL, so pair external with a string to (or an href); an object to has none and renders a dead <a> (warns in dev).",
        "default": "false"
      },
      {
        "name": "to",
        "type": "RouteLocationRaw | string | object",
        "required": false,
        "description": "Internal navigation target, handed to the resolved router link (NuxtLink, else RouterLink). When no router is installed, a string to degrades to a plain <a :href>; an object to needs a router (there is nothing sensible to put in href without one). An object to with no router to resolve it — including when external forces a plain <a> — renders a destination-less anchor and warns in dev; pass a string to/href, or install a router. Its type is a router-agnostic fallback by default and vue-router's RouteLocationRaw once the @bankai-vue/core/vue-router types augmentation is active — see BankaiLinkTo."
      },
      {
        "name": "href",
        "type": "string",
        "required": false,
        "description": "Explicit anchor target. Always renders a native <a href>, never a router link — use it for external URLs, mailto:/tel:, fragments, and downloads."
      }
    ],
    "slots": [
      {
        "name": "default",
        "description": "Link content — the label, and optionally an icon."
      }
    ],
    "events": []
  },
  "BankaiText": {
    "props": [
      {
        "name": "as",
        "type": "BankaiTextElement | string",
        "required": false,
        "description": "Element to render as. Polymorphic — suggests the phrasing/text elements (BankaiTextElement); any tag string (e.g. a custom element) is also accepted. Use an inline-semantic element ('strong', 'em', 'mark', 'code', 'kbd', 'del', …) to carry that meaning natively.",
        "default": "'span'"
      },
      {
        "name": "size",
        "type": "'xs' | 'sm' | 'md' | 'lg' | 'xl' | '2xl' | string",
        "required": false,
        "description": "Type size. A named xs–2xl step (--bankai-text-size-*) reflects as data-bankai-size; any other string is a verbatim CSS font-size. Omitted when unset (inherits the ambient font size)."
      },
      {
        "name": "weight",
        "type": "'thin' … 'black' | number | string",
        "required": false,
        "description": "Font weight. A named step (BankaiTextWeight) reflects as data-bankai-weight; a number or any other string ('var(--wght)', 'calc(…)', 'lighter') is a verbatim font-weight — a variable font renders a numeric value along its wght axis. Omitted when unset (inherits the ambient weight)."
      },
      {
        "name": "tone",
        "type": "'default' | 'muted' | 'subtle' | string",
        "required": false,
        "description": "Text tone. A named neutral tone reflects as data-bankai-tone; any other string is a verbatim CSS color. Omitted when unset (inherits the ambient color)."
      },
      {
        "name": "truncate",
        "type": "boolean",
        "required": false,
        "description": "Truncate overflowing text to a single line with an ellipsis. Reflected on the root as data-bankai-truncate. The theme rule makes the element block-level, so it truncates against the available width.",
        "default": "false"
      }
    ],
    "slots": [
      {
        "name": "default",
        "description": "Text content."
      }
    ],
    "events": []
  }
} satisfies Record<string, ComponentMeta>;
